C:/VulkanSDK/Bin32/glslc.exe shader.vert -o vert.spv
C:/VulkanSDK/Bin32/glslc.exe shader.frag -o frag.spv
C:/VulkanSDK/Bin32/glslc.exe texturedMeshShader.vert -o texturedMeshVert.spv
C:/VulkanSDK/Bin32/glslc.exe texturedMeshShader.frag -o texturedMeshFrag.spv
C:/VulkanSDK/Bin32/glslc.exe texturedMeshLighting.vert -o texturedMeshLighting.vert.spv
C:/VulkanSDK/Bin32/glslc.exe texturedMeshLighting.frag -o texturedMeshLighting.frag.spv
C:/VulkanSDK/Bin32/glslc.exe imgui.vert -o imgui.vert.spv
C:/VulkanSDK/Bin32/glslc.exe imgui.frag -o imgui.frag.spv
C:/VulkanSDK/Bin32/glslc.exe animatedMesh.vert -o animatedMesh.vert.spv
C:/VulkanSDK/Bin32/glslc.exe animatedMesh.frag -o animatedMesh.frag.spv
C:/VulkanSDK/Bin32/glslc.exe animatedMeshLighting.vert -o animatedMeshLighting.vert.spv
C:/VulkanSDK/Bin32/glslc.exe animatedMeshLighting.frag -o animatedMeshLighting.frag.spv
C:/VulkanSDK/Bin32/glslc.exe gui2d.vert -o gui2d.vert.spv
C:/VulkanSDK/Bin32/glslc.exe gui2d.frag -o gui2d.frag.spv
C:/VulkanSDK/Bin32/glslc.exe debug.vert -o debug.vert.spv
C:/VulkanSDK/Bin32/glslc.exe debug.frag -o debug.frag.spv
C:/VulkanSDK/Bin32/glslc.exe debugPicker.vert -o debugPicker.vert.spv
C:/VulkanSDK/Bin32/glslc.exe debugPicker.frag -o debugPicker.frag.spv
C:/VulkanSDK/Bin32/glslc.exe shaderLighting.vert -o shaderLighting.vert.spv
C:/VulkanSDK/Bin32/glslc.exe shaderLighting.frag -o shaderLighting.frag.spv
C:/VulkanSDK/Bin32/glslc.exe particle.vert -o particle.vert.spv
C:/VulkanSDK/Bin32/glslc.exe particle.frag -o particle.frag.spv
C:/VulkanSDK/Bin32/glslc.exe offscreenAnimatedMeshLighting.vert -o offscreenAnimatedMeshLighting.vert.spv
C:/VulkanSDK/Bin32/glslc.exe offscreenAnimatedMeshLighting.frag -o offscreenAnimatedMeshLighting.frag.spv
C:/VulkanSDK/Bin32/glslc.exe offscreenTexturedMeshLighting.vert -o offscreenTexturedMeshLighting.vert.spv
C:/VulkanSDK/Bin32/glslc.exe offscreenTexturedMeshLighting.frag -o offscreenTexturedMeshLighting.frag.spv
pause
